### ISSUE TITLE
Read all emails from last historyId after recieving Pub/Sub message

### ISSUE THREAD

**Issue by lhauspie** [Zenika/lilaobot#46]
Pub/Sub Message contains the email address and an historyId. Today we only read the last recieved email. By this way we might miss some email if several emails are recieved ate the almost same time.

It could be nice to read all the recieved email since the last historyId becaus an historyId can represent a batch of emails.

**Comment by Riduidel** [comment]
To my mind, different email will trigger different messages, but I can find no information (yet) at https://developers.google.com/gmail/api/reference/rest/v1/users/watch

**Comment by Riduidel** [comment]
Ah ok, it's at https://developers.google.com/gmail/api/guides/push#receiving_notifications

**Comment by Riduidel** [comment]
Implemented (badly) in 42c4465
