### ISSUE TITLE
Cleanup branches !

### ISSUE THREAD

**Issue by Riduidel** [Zenika/lilaobot#52]
There are at least ten branches which are not currently merged in main.
Can you please remove the branches you have created that contain code merged into main (be it directly or through a cherry-pick or any other cumbersome git-fuckery ?

Branches to analyze are

- [x] @Le-Bit by Cyril Labitte         origin/feat/prettier
- [x] @Le-Bit by Cyril Labitte         origin/fix/rework-testing
- [x] @AcevedoR       origin/fix/fix-gmail-api-mappings
- [x] @AcevedoR       origin/fix/fix-onNewMessage
- [x] @AcevedoR       origin/fix/config-import-broken
- [x] @AcevedoR       origin/feat/onNewMessage-impl
- [x] @AcevedoR       origin/fix/callback-save-token
- [x] @AcevedoR       origin/docs/add-architecture-diagram
- [x] @AcevedoR       origin/feat/adding-initWatch-function
- [x] @AcevedoR       origin/fix/callback-function
- [x] @AcevedoR       origin/feat/implementing-callback-function
- [x] @sixdouglas    origin/master-backup-with-douglas-work
- [x] @sixdouglas   origin/fix/gmailNotifierStep1

Can you either deet branch remotely or comment with the PR linked to this branch ?

**Comment by AcevedoR** [comment]
branches were not deleted while merging PR, fixed
