### ISSUE TITLE
Message may be received multiple times

### ISSUE THREAD

**Issue by Riduidel** [Zenika/lilaobot#56]
I have sent a mail to lilaobot email address, which has been sent 4 times to Slack. maybe we could avoid that, no?

**Comment by Riduidel** [comment]
See also

* https://developers.google.com/gmail/api/reference/rest/v1/users.history/list#History (a method we mabye should call)
* https://developers.google.com/gmail/api/reference/rest/v1/users/watch (the method we indeed call, according to @AcevedoR )

**Comment by AcevedoR** [comment]
fixed, but now the last issue is on forwarded mails being duplicated

**Comment by AcevedoR** [comment]
to follow here #71
